List<String> wordList = [
  "'A' Stage",
  "AB",
  "ABCD parameters",
  "ABP",
  "abrasion resistance",
  "absolute maximum ratings",
  "absolute temperature scale",
  "absorbing clamp",
  "absorption",
  "absorptive device",
  "absorptive filter",
  "AC",
  "AC filter",
  "AC flux density",
  "ACA",
  "accelerated aging",
  "accelerator",
  "acceptance angle",
  "acceptor",
  "access method",
  "access provider",
  "access rate",
  "access time",
  "accessories",
  "accumulator",
  "ACR",
  "Action Pin contact",
  "active device",
  "active element",
  "active high",
  "active low",
  "active network",
  "active substrate",
  "A-D converter",
  "ADA",
  "adapter",
  "adder",
  "address",
  "address field",
  "adhesive",
  "adhesive liner",
  "admittance",
  "ADSL",
  "AFC",
  "AGC",
  "aging",
  "A-GPS",
  "AI",
  "air core inductance",
  "air gap",
  "AL value",
  "aliphatic hydrocarbons",
  "alloy",
  "alphanumeric",
  "Alternating Current",
  "altitude immersion seal",
  "alumina",
  "aluminum oxide",
  "AM",
  "ambient temperature",
  "American Society for Testing and Materials",
  "American Wire Gauge",
  "ammeter",
  "amnesia",
  "amorphous",
  "AMP",
  "ampacity",
  "AMP-Duragold",
  "ampere",
  "ampere turns",
  "ampere-turns per meter",
  "amplifier",
  "amplitude",
  "Amplitude Modulation",
  "amplitude permeability",
  "AMPS",
  "analog",
  "analog computer",
  "and gate",
  "anechoic chamber",
  "Angstrom",
  "angular misalignment",
  "anisotropic",
  "anneal",
  "anode",
  "anodize",
  "ANSI",
  "ANSI T1.403",
  "ANSI T1.413",
  "antenna",
  "antistatic",
  "anvil",
  "APD",
  "applicator",
  "arc resistance",
  "ARINC",
  "Arithmetic and Logic Unit",
  "Artificial Intelligence",
  "artwork",
  "AS/400",
  "ASCII",
  "ASE",
  "ASIC",
  "ASP",
  "asperities",
  "a-spots",
  "assembler",
  "assembly language",
  "assymetrical transmission",
  "ASTM",
  "asynchronous",
  "asynchronous transmission",
  "ATE",
  "ATM",
  "attenuation",
  "attenuation-limited operation",
  "attenuator",
  "atto",
  "audio amplifier",
  "autoclaves",
  "Automatic Frequency Control",
  "Automatic Gain Control",
  "avalanche photodiode",
  "avionics",
  "AVL",
  "AWG",
  "'B' stage",
  "B &amp; S",
  "B channel",
  "back mounted",
  "backboard",
  "backbone",
  "backbone cabling",
  "backbone network",
  "back-mounted",
  "backplane",
  "backscattering",
  "bail lock",
  "balanced line",
  "balanced mixer",
  "balanced transmission line",
  "ball bond",
  "ballast",
  "balun",
  "balun filter",
  "band marking",
  "Band Pass",
  "Band Pass Filter",
  "Band Reject Filter",
  "Band Stop",
  "bandwidth",
  "Bandwidth-limited operation",
  "Bare Conductor",
  "barrel",
  "barrier block",
  "Barrier Height",
  "base",
  "Base Current",
  "base metal",
  "Base Plate",
  "Base Plate Temperature",
  "Base Resistance",
  "Base Transceiver Station (or Base Station)",
  "Baseband",
  "baseband signal",
  "BASIC",
  "Basic Encoding Rate (BER)",
  "Basic Rate Interface (BRI)",
  "Batch Number",
  "Battery Backup",
  "baud",
  "bayonet coupling",
  "bcd",
  "beam lead",
  "Beaming",
  "Beamsplitter",
  "Bel",
  "bellmouth",
  "Bend loss",
  "BER",
  "bezel",
  "B-H Curve",
  "BH Loop",
  "BHMAX (Maximum Energy Product)",
  "Bias",
  "Bias Current",
  "bias voltage",
  "BiCMOS",
  "Bifilar Winding",
  "bifurcated contact",
  "Bilateral",
  "binary",
  "binary code",
  "binary coded decimal",
  "Binder",
  "bipolar",
  "Birmingham Wire Gauge",
  "bistable",
  "bit",
  "bit density",
  "Bit Error Rate",
  "Bits Per Second (bps)",
  "black box",
  "BLEC",
  "blistering",
  "block",
  "blocking",
  "Bluetooth",
  "BNC",
  "BNC Series",
  "bobbin",
  "bobbin core",
  "body",
  "bond pull",
  "bond strength",
  "bond wire",
  "bonding",
  "bonding area",
  "bonding pad",
  "bonding temperature",
  "Boolean algebra",
  "boost regulator",
  "boot",
  "bootstrap",
  "bounce time",
  "BPF",
  "bpi",
  "BPSK",
  "braid",
  "Braid Angle",
  "branched",
  "breadboard",
  "breadboard circuit",
  "breakdown voltage",
  "Breakout",
  "Breakover Current",
  "Breakover Voltage",
  "breakpoint",
  "BRF",
  "bridge converter",
  "bridge/router",
  "bridging",
  "British Standard Wire Gauge",
  "brittle temperature",
  "broadband",
  "broadband EMI",
  "broadband signal",
  "brush",
  "BSP",
  "BTS",
  "bubble",
  "bubble memory",
  "buck boost converter",
  "buck derived converter",
  "buck regulator",
  "buffer",
  "buffer coating",
  "buffer tube",
  "bulk storage memory",
  "bulkhead",
  "buna rubber",
  "bunch stranding",
  "burn in",
  "burnout",
  "bus",
  "bus bar",
  "bus network",
  "bus reactor",
  "bus-powered",
  "butt",
  "butt gap",
  "butt splice",
  "bypass filter",
  "byte",
  "'C' stage",
  "C/A",
  "cable",
  "cable assembly",
  "cable clamp",
  "cable clamp",
  "cable clamp adapter",
  "cable modem",
  "cable sealing clamp",
  "cabler",
  "cabling",
  "CAD",
  "calender",
  "CAM",
  "camber",
  "campus area network",
  "Canadian Standards Association",
  "CAP",
  "capacitance",
  "capacitive coupling",
  "capacitive decoupling",
  "capacitive reactance",
  "capacitor",
  "CAPs",
  "Carbonyl Iron",
  "card image",
  "carrier",
  "carrier sense multiple access with collision detection",
  "carrier suppression",
  "cascade",
  "case",
  "case temperature",
  "catalyst",
  "catastrophic failure",
  "Category 3",
  "Category 5",
  "Category 5e",
  "Category 6",
  "cathode",
  "cathode-ray tube",
  "CATV",
  "cavity",
  "CCD",
  "CCITT",
  "CDI",
  "CDMA",
  "CDPD",
  "cellular",
  "center fastener",
  "centi",
  "central processing unit",
  "centro-symmetrical reflective optics",
  "ceramic",
  "ceramic cores",
  "ceramic-based microminiature circuitry",
  "cermet",
  "CFM",
  "CGI",
  "chain length",
  "channel",
  "character",
  "characteristic impedance",
  "chemical resistance",
  "chemically deposited printed circuit",
  "chemically reduced printed circuit",
  "Cheminax cables",
  "chip",
  "chip carrier",
  "choke",
  "churn",
  "circuit",
  "circuit element",
  "circuit speed",
  "circuit switching",
  "Circuit-Switched Network",
  "circular mil area",
  "circular mils (cm)",
  "Circulator",
  "cladding",
  "Cladding mode",
  "clear",
  "CLEC",
  "Client/Server",
  "clock",
  "Clocking",
  "Close Magnetic Path",
  "closed barrel",
  "closed circuit",
  "closed end splice",
  "closed entry contact",
  "closed loop",
  "Closed Magnetic Path",
  "CMA",
  "CMG",
  "CMOS",
  "CMTS",
  "CO",
  "coax",
  "coaxial cable",
  "coaxial ribbon cable",
  "COBOL",
  "Coder/Decoder (Codec)",
  "coefficient of expansion",
  "Coercive Force (HC)",
  "COFDM",
  "co-fire",
  "COG",
  "coil",
  "Coil Hi-Pot",
  "Coil Resistance",
  "Coils",
  "Cold Bend",
  "cold flow",
  "Cold Impact",
  "cold joint",
  "cold weld",
  "cold work",
  "Collector",
  "Collector Current",
  "Color Code",
  "color coding",
  "color concentrates",
  "Color Stability",
  "command",
  "Common",
  "Common Carrier",
  "Common Mode Current",
  "Common Mode Filter (or Choke)",
  "Common Mode Noise",
  "Common Mode Noise",
  "Common Mode Type I",
  "Common Mode Type II",
  "Common Mode Voltage",
  "common-mode EMI",
  "common-mode impedance coupling",
  "compiler",
  "complement",
  "component",
  "compound",
  "Compound Under Strands",
  "Compression",
  "compression molding",
  "compression set",
  "computer",
  "computer, off-line",
  "computer, on-line",
  "Concentrator",
  "concentric",
  "Concentric Stranding",
  "Concentricity",
  "Conditioned Analog Line",
  "Conductance",
  "Conduction Cooled",
  "conductive composite",
  "conductive fillers",
  "conductive pattern",
  "conductive plastics",
  "Conductive Polymer",
  "Conductivity",
  "Conductor",
  "Conductor Resistance",
  "Conduit",
  "Configuration",
  "confined (C) crimp",
  "confined crescent (CC) crimp",
  "connector",
  "connector assembly",
  "Connector Classes",
  "Connector Insert",
  "Consolidation point",
  "Contact",
  "contact alignment",
  "contact area",
  "Contact Arrangement",
  "contact bounce",
  "Contact Capacitance",
  "contact cavity",
  "Contact Crimp",
  "contact durability",
  "contact engaging and separating force",
  "contact float",
  "Contact Form",
  "contact inspection hole",
  "contact rating",
  "contact resistance",
  "contact retention",
  "contact shoulder",
  "contact size",
  "contact spacing",
  "contact spring",
  "contact wipe",
  "contact, bellows",
  "contact, two-piece",
  "contents",
  "continuity",
  "Continuous Current",
  "Continuous Operating Temperature",
  "Continuous Service",
  "Continuous Shield",
  "Continuous Wave",
  "control unit",
  "Control Winding",
  "controlled part",
  "controller",
  "Convection Cooled",
  "Conversion Loss",
  "copolymer",
  "Copper Loss",
  "Copper Loss",
  "CopperOptics",
  "cordwood",
  "Core",
  "Core Constant",
  "Core Losses",
  "Core Saturation",
  "Corner Frequency",
  "corona",
  "counter",
  "Coupler",
  "Coupling Factor",
  "Coupling Ring",
  "coupon",
  "Cover, Electrical Connector",
  "Coverage",
  "CPE",
  "CPU",
  "creep",
  "creepage",
  "creepage path",
  "crimp",
  "crimp contact",
  "crimp height",
  "crimper",
  "crimping chamber",
  "Crimping Die",
  "crimping dies",
  "crimping head",
  "crimping tool",
  "Critical Rate of Rise of Off-State Voltage",
  "Critical Rate of Rise of On-State Current",
  "Cross connect (XC)",
  "cross crimp",
  "Cross Regulation",
  "cross-linked",
  "Crosslinking",
  "Crosslinking by Irradiation",
  "crossover",
  "crosstalk",
  "Crowbar",
  "CRT",
  "CRT display",
  "crush crimp",
  "Crystallinity",
  "CSA",
  "CSMA/CD",
  "CSR",
  "CSU/DSU",
  "Cuk Converter",
  "cure",
  "Curie Temperature",
  "Curing",
  "curing agents",
  "curing cycle",
  "current",
  "Current Density",
  "Current Foldback",
  "current gain",
  "Current Limit",
  "Current Limit Knee",
  "Current Limiting",
  "Current Mode Control",
  "Current Rating",
  "Current Transformer",
  "Current,Hold",
  "Current,Maximum Interrupt",
  "Current,Normal Operating",
  "Current,Operating Range",
  "Current,Trip",
  "Current-carrying Capacity",
  "current-mode logic",
  "CUS",
  "cutoff frequency",
  "cutoff tab",
  "Cutoff wavelength",
  "Cutout",
  "Cut-through Resistance",
  "CW",
  "cycle",
  "D Channel",
  "D-AMPS",
  "Dark current",
  "Data Circuit-terminating Equipment",
  "Data rate",
  "Data rate",
  "Data Terminal Equipment (DTE)",
  "dB",
  "dBm",
  "DBS",
  "dbtt",
  "DC",
  "DC Bias",
  "DC Filter",
  "DC Stress",
  "DC-DC Converter",
  "DCE",
  "DCR",
  "DCS 1800",
  "DCS 1900",
  "deci",
  "Decibel",
  "Decoupling",
  "DECT",
  "Dedicated Line",
  "deka",
  "Delay Line",
  "Delay skew",
  "Delta",
  "Demagnetization Curve",
  "Demagnetized",
  "Demodulation",
  "Density",
  "Depletion Layer",
  "Derating",
  "Desensitization",
  "Detector",
  "DGPS",
  "Dial up",
  "Diameter-mismatch loss",
  "Dichroic filter",
  "Dielectric",
  "Dielectric Breakdown",
  "Dielectric Constant",
  "Dielectric Loss",
  "Dielectric Strength",
  "Dielectric Strength - Electric Strength - Hipot",
  "Dielectric Withstand Voltage",
  "Differential Mode",
  "Differential Mode Current",
  "Differential Mode Noise",
  "Differential Mode Voltage",
  "Diffraction grating",
  "Diffusion",
  "Digital",
  "Digital Signal 0 (DS-0)",
  "Digital Signal 1 (DS-1)",
  "Diode",
  "Diplexer",
  "Diplexing",
  "Direct Current",
  "Direct Current Resistance",
  "Direction of Lay",
  "Directional Coupler",
  "Disable",
  "Disaccommodation (DF)",
  "Discontinuity",
  "Discrete",
  "Discrete Air Gap",
  "Discriminator",
  "D-ISDN",
  "Dispersion",
  "Dissipation",
  "Dissipation Factor",
  "Distortion",
  "Distortion-limited operation",
  "Distributed Air Gap",
  "Distributed Capacitance",
  "Distributed Inductance",
  "Distributed Power",
  "DLC",
  "DLEC",
  "DMA",
  "DMT",
  "DOCSIS",
  "DoD",
  "Donor",
  "DOP",
  "Dopant",
  "Doping",
  "Doppler Effect",
  "Doppler Radar",
  "Doppler Shift",
  "Double Balanced Mixer",
  "Downconverter (Mixer)",
  "DQPSK",
  "DR",
  "Drain",
  "Drain Wire",
  "Drift",
  "Driver",
  "Drop",
  "Drop Cable",
  "Drop-out Voltage",
  "DSL",
  "DSLAM",
  "DSP",
  "DSSS",
  "DTK",
  "Duplex",
  "Duplex cable",
  "Duplex transmission",
  "Duplexer",
  "Duroid",
  "Dust Cover",
  "Duty Cycle",
  "DWDM",
  "DWV",
  "Dynamic Load",
  "Dynamic Range",
  "Dynamic Response",
  "E",
  "E1",
  "E3",
  "EAROM",
  "EBCDIC",
  "ECCM",
  "E-CGI",
  "Echo Cancellation",
  "ECL",
  "ECM",
  "eco",
  "Eddy Current Losses",
  "EDFA",
  "EDGE",
  "edge connector",
  "edge pad",
  "edge-mount connector",
  "Effective Area",
  "Effective Length",
  "Effective Permeability",
  "Effective Volume",
  "Efficiency",
  "egg crating",
  "EGNOS",
  "EID",
  "Elastic Memory",
  "elastomer",
  "Electric Current",
  "Electric Field",
  "Electrical Length",
  "Electricity",
  "electroless plating",
  "Electromagnetic Field",
  "Electromagnetic Interference",
  "Electromagnetic Radiation",
  "Electromotive Force",
  "Electron",
  "Electronic Counter-countermeasures",
  "Electronic Countermeasures",
  "Electronic Intelligence",
  "electronic interference",
  "Electronic Warfare",
  "Electronics",
  "electrostatic discharge",
  "Electrostatic Discharge",
  "Electrostatic Sensitivity",
  "Electrostatic Shield",
  "electro-tinned",
  "ELFEXT",
  "ELINT",
  "Elongation",
  "embossing",
  "EMC",
  "EMD",
  "emf",
  "EMI",
  "EMI Filter",
  "Emitter",
  "Emitter Bias",
  "Emitter Current",
  "emitter-coupled logic",
  "emulator",
  "Enable",
  "Enable High/Low",
  "Encapsulant",
  "encapsulation",
  "Enclosure",
  "encoder",
  "End",
  "end of message",
  "Energy Storage (.5LI2)",
  "Energy Storage Inductors",
  "engaging force",
  "Enhanced Category 5",
  "Enterprise Network",
  "environment",
  "environmentally sealed",
  "EOM",
  "E-OTD",
  "EPE",
  "Epitaxial",
  "epitaxial layer",
  "epoxy",
  "EPROM",
  "EPSRC",
  "equilibrium mode distribution",
  "Equivalent Series Inductance (ESL)",
  "Equivalent Series Resistance (ESR)",
  "Erbium-doped fiber amplifier",
  "Error Amplifier",
  "ESCON",
  "ESD",
  "ETA",
  "etchant",
  "etched wire",
  "etched wiring substrate",
  "etching",
  "ETE",
  "ETFE",
  "Ethernet",
  "ethylenepropylene rubber",
  "Eutectic Solder",
  "Evaporation",
  "EW",
  "exa",
  "Excess loss",
  "Excitation Current",
  "excite",
  "executive control program",
  "Expanded ID",
  "Expansion Ratio",
  "extender",
  "external storage",
  "extraction tool",
  "Extrinsic loss",
  "extrinsic properties",
  "extrinsic semiconductor",
  "Extrusion",
  "eyelet",
  "F connector",
  "F crimp",
  "face",
  "face seal",
  "Failure",
  "Failure Analysis",
  "Failure Criteria",
  "failure mechanism",
  "Failure Mode",
  "Failure Rate",
  "Fall time",
  "Fan Cooled",
  "fan in",
  "fan out",
  "Farad",
  "Faraday Shield",
  "fatigue",
  "Fault Mode Current",
  "FCC",
  "FDDI",
  "FDM",
  "FDMA",
  "Federal Communications Commission",
  "Feed Forward",
  "Feedback",
  "Feedback Loop",
  "Feedback Path",
  "feedthrough",
  "feedthrough capacitor",
  "femto",
  "FEP",
  "Ferrite Bead",
  "Ferrite Core",
  "Ferromagnetism",
  "Ferroresonat Transformer",
  "ferrule",
  "FET",
  "FET resistor",
  "FEXT",
  "ffc",
  "Fiber Channel",
  "Fiber Distributed Data Interface network",
  "Fiber Optic Cable",
  "Fiber Optics",
  "Fiber-Optic Interrepeater Link",
  "field",
  "Field Effect Transistor",
  "Field Strength (H)",
  "file",
  "file maintenance",
  "filled cable",
  "Filler",
  "film",
  "film resistors",
  "Filter",
  "Fine Leak Test",
  "firmware",
  "fishpaper",
  "Flag",
  "Flag delay time",
  "flag terminal",
  "flame resistance",
  "Flame Retardant",
  "flame retardants",
  "Flame-resistant",
  "flammability",
  "flange",
  "flash",
  "Flat Braid",
  "Flat Cable",
  "Flat Conductor",
  "flat pack",
  "Flatness",
  "Flex Life",
  "flexibilizer",
  "flexible substrate",
  "flip-chip",
  "flip-flop",
  "floating bushing",
  "floating ground",
  "Floating Output",
  "Flow Soldering",
  "FLP",
  "fluorocarbons",
  "fluoroplastics",
  "Fluoropolymer",
  "Flux",
  "Flux Density (B)",
  "Flux Transfer Ratio",
  "Flyback",
  "Flyback Converter",
  "Flyback Transformer",
  "FM",
  "FOIRL",
  "Foldback Current Limiting",
  "Forced Air Cooling",
  "FORTRAN",
  "Forward Bias",
  "Forward Converter",
  "Forward Converter Transformer",
  "FPGA",
  "FQPSK",
  "Fractional T1",
  "frame",
  "Frame Relay",
  "Free Convection",
  "free hanging",
  "free standing",
  "Frequency",
  "Frequency Band",
  "Frequency Conversion",
  "Frequency Converter (or simply, Converter)",
  "Frequency Modulation",
  "Frequency Multiplication",
  "Frequency of Operation",
  "frequency response",
  "frequency, voice",
  "Fresnel reflection",
  "Fresnel reflection loss",
  "fretting corrosion",
  "Fringing Fields or Fringing Flux",
  "Front Release Contacts",
  "front-mounted",
  "FSK",
  "Full Bridge",
  "Full Bridge Converter",
  "Full Load",
  "Full Load Voltage",
  "Full Recovery Temperature, Minimum",
  "Full Winding",
  "Full-Wave Rectifier",
  "function",
  "Fundamental Frequency",
  "funnel entry",
  "Fuse",
  "Fused coupler",
  "GaAs Field Effect Transistor",
  "gage element",
  "gage member",
  "Gain",
  "Gain Control",
  "galvanic corrosion",
  "Ganged port protection",
  "Gap loss",
  "garbage",
  "GAST",
  "gate",
  "gate array",
  "Gauge",
  "Gauss",
  "Gbps",
  "GDOP",
  "generator",
  "GEO",
  "g-force",
  "GGA",
  "giga",
  "Gigabit Ethernet",
  "Gigabits Per Second (Gbps)",
  "GIGO",
  "Gilbert",
  "GIS",
  "Glass Microwave Integrated Circuit",
  "GMIC",
  "GNSS",
  "Government Rubber Synthetic",
  "GPRS",
  "GPS",
  "Graded Cores",
  "graded index fiber",
  "Graded-index fiber",
  "Grain Oriented",
  "Gray code",
  "green ceramic",
  "grid",
  "grid-spaced",
  "grommet",
  "ground",
  "Ground fault",
  "Ground Loop",
  "ground loop noise",
  "Ground Plane",
  "Grounding Conductor",
  "Ground-loop noise",
  "Group Delay",
  "GSA",
  "GSM",
  "GSV",
  "guard band",
  "guide pin and socket",
  "Gunn Effect",
  "H",
  "h Parameters",
  "Half Bridge",
  "Half Bridge Converter",
  "Half-Wave Rectifier",
  "Hall effect",
  "Hall Effect Transducer",
  "handshake",
  "hard copy",
  "Hard Magnetic Material",
  "Hardness",
  "hardware",
  "Harmonic Content",
  "Harmonics",
  "harness",
  "HDOP",
  "HDSL",
  "Headend",
  "header",
  "Heat Aging",
  "Heat Flux",
  "heat guns",
  "heat resistant",
  "Heat Shock",
  "Heat Sink",
  "heat sink tab",
  "heat-shrinkable",
  "Heat-Shrinkable Material",
  "hecto",
  "Henry",
  "hermaphroditic connector",
  "hermaphroditic contact",
  "hermetic",
  "hermetic seal",
  "Hermeticity",
  "hertz",
  "Heterolithic Microwave Integrated Circuit'",
  "hexadecimal numbering system",
  "HFC",
  "hi temp",
  "Hiccup Mode",
  "High Line",
  "High Pass Filter",
  "High Potential Test (Hi-Pot Test)",
  "High Q Filters",
  "high voltage",
  "high-density polyethylene",
  "high-level logic",
  "high-speed socket",
  "Hi-Rel Screening",
  "HMIC",
  "Hold Current",
  "Hold Current Minimum",
  "Hold Voltage",
  "holding strength",
  "Hold-Up Time",
  "Hole",
  "hole conduction",
  "holes",
  "Hollerith",
  "hook tongue",
  "Hookup Wire and Cable",
  "Horizontal cabling",
  "hot melts",
  "Hot Plug-In",
  "Hot-Melt Adhesive",
  "Hot-Plug",
  "housing",
  "HPF",
  "Hub",
  "Humidity Aging Test",
  "Humidity Aging Test",
  "hybrid",
  "hybrid IC",
  "hygroscopic",
  "Hysteresis and Hysteresis Loss",
  "Hysteresis Loop",
  "Hz",
  "I",
  "I/O",
  "I/O limited",
  "IAD",
  "IC",
  "ICP",
  "ID",
  "IDC",
  "identifier",
  "IDP",
  "IDSL",
  "IEC",
  "IEEE",
  "IEEE 488",
  "IEEE 802.3",
  "IEEE 802.5",
  "IF",
  "IF Bandwidth",
  "IF Impedance",
  "IGFET",
  "IH",
  "IHOLD",
  "IIL",
  "ILEC",
  "Image Frequency",
  "Image Rejection Mixer",
  "Imax",
  "IMPATT",
  "Impedance",
  "impedance match",
  "Impedance Matching",
  "Imperial Wire Gauge",
  "impregnate",
  "Impulse Test",
  "In Phase",
  "Incident Wave",
  "Incremental Current",
  "Incremental Permeability (?inc)",
  "Index of refraction",
  "Index-matching material",
  "Individual Port Protection",
  "Inductance",
  "Inductance Factor (AL)",
  "induction generator",
  "induction motor",
  "inductive coupling",
  "Inductive Reactance",
  "Inductor",
  "information channel",
  "inhibiting input",
  "inhibitor, corrosion",
  "Initial Permeability (NO)",
  "Initial Resistance",
  "initialize",
  "Input",
  "input bias current",
  "Input Current",
  "input impedance",
  "Input Line Filter",
  "input offset current",
  "input offset voltage",
  "Input Reflected Ripple Current",
  "Input Surge Current",
  "Input Transient",
  "Input Voltage Range",
  "Inrush Current",
  "Inrush Current Limiting",
  "insert",
  "Insert Arrangement",
  "Insert Cavity",
  "insert molding",
  "insertion force",
  "insertion loss",
  "insertion tool",
  "Inspection Hole",
  "Institute of Electrical and Electronic Engineers",
  "instruction",
  "Insulated Gate Bipolar Transistor",
  "Insulated Terminal",
  "Insulating Layer",
  "insulation",
  "insulation barrel",
  "insulation crimp",
  "insulation displacement",
  "insulation grip",
  "insulation piercing",
  "Insulation Resistance",
  "insulation support",
  "Insulation, Electrical",
  "Insulation, Thermal",
  "integrated circuit",
  "integrated circuitry",
  "Integrated detector/preamplifier",
  "interaction",
  "Intercept Point",
  "interchangeable",
  "Interconnection",
  "Interface",
  "interfacial compression",
  "interfacial connection",
  "interfacial gap",
  "interfacial junction",
  "interfacial seal",
  "interference protection",
  "interlaced memory",
  "intermateable",
  "Intermediate Frequency",
  "Intermodulation Distortion",
  "Intermodulation Frequencies",
  "Internal Diameter",
  "Internal Power Dissipation",
  "International Electrotechnical Commission",
  "Interstice",
  "Intranet",
  "inverter",
  "Inverter Transformer",
  "Ion Implantation",
  "ionomer",
  "IP",
  "Iron-Core Coil/Transformer",
  "IRQ",
  "Irradiation",
  "IS-95",
  "Isc Max",
  "ISDN",
  "ISO",
  "Isolated Output",
  "Isolation",
  "Isolation Capacitance",
  "isolation diffusion",
  "Isolation Resistance",
  "Isolation Transformer",
  "Isolation Voltage",
  "Isolator",
  "Isotropic",
  "ISP",
  "IT",
  "ITAR",
  "ITS",
  "ITU",
  "I-V Transfer Characteristics",
  "IXC",
  "jack",

  // !
  // !
  "Jacket",
  "jackscrew",
  "JAN specification",
  "jitter",
  "Jones block",
  "Joule",
  "jumper",
  "Junction",
  "Kapton",
  "Kbps",
  "kcmil",
  "Kelvin Scale",
  "key",
  "keying",
  "keying plug",
  "keyway",
  "kilo",
  "Kilobits per second (kbps)",
  "Kilovolt",
  "KMER",
  "Knee (of the demagnetization curve)",
  "Kool Mu",
  "Kovar",
  "KPR",
  "Ku-Band",
  "Kulka block",
  "kV",
  "Kynar",
  "L1",
  "L2",
  "L3",
  "L5",
  "LAAS",
  "label",
  "Lacing Cord or Twine",
  "Lambda",
  "Laminated Cores",
  "laminating",
  "Laminations",
  "LAN",
  "land",
  "Lanyard",
  "large-scale computer",
  "large-scale integration",
  "Laser",
  "laser diode",
  "Last mile",
  "Lateral displacement loss",
  "Lay",
  "Lay Length",
  "layout",
  "L-Band",
  "LCD",
  "lead frame",
  "lead(s)",
  "leading edge",
  "Leakage Current",
  "Leakage Inductance",
  "Leased Line",
  "LEC",
  "LED",
  "LEO",
  "Levels of packaging",
  "LFM",
  "Life Cycle",
  "Life test",
  "Lifeline POTS",
  "light-emitting diode",
  "Limiter",
  "Line",
  "Line Code",
  "line cord",
  "Line Effect",
  "line impedance",
  "line printer",
  "Line Regulation",
  "Line transient",
  "Linear",
  "linear circuit",
  "Linear Material",
  "linear polymer",
  "Linear Power Transformer",
  "Linear regulation",
  "Linearity",
  "Liner",
  "link",
  "Litz Wire",
  "LMDS",
  "LNA",
  "LO",
  "Load",
  "Load Decoupling",
  "Load Life",
  "Load Life, Rated Resistive",
  "Load Loss",
  "Load Regulation",
  "local area network",
  "Local Area Transport Area",
  "Local Loop",
  "Local Oscillator",
  "Local sensing",
  "locator",
  "logic",
  "logic gate",
  "Logic Inhibit/Enable",
  "Long Term Stability",
  "Longitudinal Change",
  "loom",
  "loose piece",
  "LORAN",
  "Loss",
  "Loss Factor",
  "lossy",
  "Lot Number",
  "Low Line",
  "Low Noise Amplifier",
  "Low Pass Filter",
  "low-density polyethylenes",
  "low-level logic",
  "Low-loss Dielectric",
  "LPF",
  "LSI",
  "Lug",
  "lumped-element filter",
  "MAC",
  "machine language",
  "macroinstruction",
  "Mag-Mate",
  "Magnet Wire",
  "Magnetic Energy",
  "Magnetic Lines Of Force",
  "Magnetic Path",
  "Magnetic Path Length",
  "main frame",
  "Majority Carrier",
  "Manufacturing Order",
  "Marking",
  "mask",
  "mass termination",
  "master pattern",
  "Master/Slave Operation",
  "matched impedance",
  "mate",
  "Material dispersion",
  "Material Modification Code",
  "mating face",
  "matrix",
  "Maximum Ambient Operating Temperature",
  "Maximum Ambient Operating Temperature",
  "Maximum Device Voltage",
  "Maximum Fault Current",
  "Maximum Interrupt Current",
  "Maximum Interrupt Voltage",
  "Maximum Load",
  "Maximum Operating Voltage",
  "Maximum Output Resistance",
  "Maximum Power Dissipation",
  "Maximum Resistance",
  "Maximum Resistance",
  "Maximum Switching Current",
  "Maximum Voltage",
  "Maxwell",
  "Mbps",
  "MCM",
  "MCNS",
  "MDS",
  "MDU",
  "Mean Time Between Failure",
  "Mean Time to Failure",
  "Mechanical Life",
  "mechanized assembly",
  "Media I",
  "Media II",
  "medium-scale integration",
  "mega",
  "Megarad",
  "melt index",
  "Melt/Flow Index",
  "Melting Point",
  "memory",
  "MEO",
  "message",
  "Metal Semiconductor Field Effect Transistor",
  "metallization",
  "Metal-Oxide-Semiconductor-Field-Effect-Transistor",
  "metric prefixes",
  "Metropolitan Area Network",
  "mho",
  "MHz",
  "MIC",
  "micro",
  "microcomputer",
  "microelectronics",
  "microminiature circuitry",
  "microminiaturization",
  "Micron",
  "microprocessor",
  "Microstrip",
  "Microwatt",
  "Microwave Distribution System",
  "Microwave Integrated Circuit",
  "microwaves",
  "MID",
  "migration",
  "Mil",
  "Military Specification",
  "Milking Off",
  "milli",
  "millisecond",
  "Milliwatt",
  "MIL-SPEC",
  "MIM",
  "miniaturization",
  "minicomputer",
  "Minimum Discernable Signal",
  "Minimum Full Recovery Temperature",
  "Minimum Load",
  "Minimum Operating Temperature",
  "Minimum Shrink Temperature",
  "Minority Carrier",
  "Misalignment loss",
  "Mismatch",
  "Mismatch Loss",
  "Mixer",
  "MLT",
  "MMDS",
  "MMIC",
  "mnemonic language",
  "MO",
  "MOD Code",
  "modal dispersion",
  "Mode",
  "Mode of Failure",
  "modem",
  "modifier",
  "modular",
  "Modular jack",
  "Modular plug",
  "modulate",
  "Modulation",
  "Modulation Frequency",
  "Modulation Sensitivity",
  "module",
  "modulus",
  "mold",
  "molecular electronics",
  "MOM",
  "monolithic integrated circuit",
  "Monolithic Microwave Integrated Circuit",
  "monomer",
  "Monotonicity",
  "MOS IC",
  "MOS transistor",
  "MOSFET",
  "motherboard",
  "mother-daughter board connector",
  "MPEG",
  "MPLS",
  "MPP Core",
  "MS",
  "MSAS",
  "MSI",
  "MTBF",
  "MT-RJ",
  "MTSAT",
  "MTTF",
  "MTU",
  "multichip IC",
  "Multiconductor",
  "Multifilar Winding",
  "multilayer board",
  "Multimate",
  "Multimode",
  "multimode fiber",
  "Multiple-Conductor Cable",
  "multiplex",
  "multiplexer",
  "Multiplier",
  "multiprogramming",
  "Multi-user outlet",
  "MUTOA",
  "MUX",
  "mW",
  "MW",
  "n region",
  "N Series",
  "NAB",
  "nail head bonding",
  "NAND gate",
  "nano",
  "Nanosecond",
  "Narrow Band",
  "narrow-band EMI",
  "Natural Rubber",
  "NAVSTAR",
  "NBR",
  "NBR/PVC",
  "NC",
  "NCC",
  "NDIS",
  "NEC",
  "Negative feedback",
  "negative logic",
  "NEMA",
  "neon",
  "neoprene rubber",
  "Network Analysis",
  "Network Interface Card",
  "Network Management System",
  "network-leased line",
  "network-private wire",
  "network-telephone",
  "network-teletype",
  "NEXT",
  "next higher assembly",
  "NIC",
  "Nick",
  "Nitrile-Butadiene Rubber",
  "NMEA",
  "NMOS",
  "NO",
  "No Load Loss (Core Losses)",
  "No Load Voltage",
  "NOC",
  "node",
  "noise",
  "Noise Figure",
  "Noise Floor",
  "Noise margin",
  "Nominal",
  "Nominal Value",
  "Non-Harmonic Signals",
  "Nonlinear Material",
  "Non-Linearity",
  "Non-recurring Engineering",
  "NOR gate",
  "Normal Operating Current",
  "NOT",
  "npn transistor",
  "NRE",
  "NRZ data rates",
  "ntc",
  "n-type",
  "n-type conductivity",
  "N-type Material",
  "n-type semiconductor",
  "numerical aperture",
  "numerical control",
  "nylon",
  "OCR",
  "O-crimp",
  "octal",
  "Octave",
  "Octave Band",
  "OD",
  "OEM",
  "Oersted",
  "off-line memory",
  "Off-Line Power Supply",
  "offset current",
  "Off-State Capacitance",
  "Off-State Current",
  "Off-State Voltage",
  "OFT",
  "ohm",
  "Ohm's Law",
  "ohms per square",
  "olefin",
  "on-line memory",
  "On-State Current",
  "On-State Voltage",
  "open barrel",
  "Open Circuit Inductance (LO)",
  "open loop",
  "Open Systems Interconnection(OSI)",
  "Open-Circuit Voltage",
  "operand",
  "Operate Time",
  "Operating Range Current",
  "operating system",
  "Operating Temperature",
  "Operating Temperature Range",
  "operating time",
  "operational amplifier",
  "optical character recognition",
  "optical fiber",
  "Optional Flame Test",
  "OQPSK",
  "OR gate",
  "oscillator",
  "OSS",
  "Outlet",
  "output",
  "Output Current Limiting",
  "Output Filter",
  "Output Impedance",
  "Output Ripple and Noise",
  "Output Voltage",
  "Output Voltage Accuracy",
  "Output Voltage Range",
  "ovaled",
  "Overcurrent Protection",
  "Overload Protection",
  "Overshoot",
  "Overtemperature Protection",
  "Overvoltage",
  "Overvoltage Lockout",
  "Overvoltage Protection (OVP)",
  "OVLO",
  "OXC",
  "oxide",
  "Oxide Passivation",
  "oxygen index",
  "ozone",
  "P1dB",
  "PA",
  "Package",
  "Packaging",
  "Packet",
  "Packet Switched Network",
  "packet switching",
  "pad",
  "Pair Gain",
  "PAL",
  "PAN",
  "Panel",
  "panel mount",
  "parallel circuit",
  "parallel operation",
  "parallel splice",
  "Parameter",
  "PARD",
  "parity",
  "parity bit",
  "parity check",
  "parts density",
  "Pascal",
  "Passband",
  "Passband Ripple",
  "Passivation",
  "Passive",
  "Passive Aging Test",
  "Passive Components",
  "Passive Device",
  "passive element",
  "Passive Network",
  "passive substrate",
  "Patch cord",
  "Patch panel",
  "patchcord programming system",
  "path",
  "Path Loss",
  "PBX",
  "PC",
  "PCB",
  "PCCL",
  "pcm",
  "PCN",
  "PCS",
  "Pd",
  "PDOP",
  "Peak On-state Surge Current",
  "Peak Power",
  "Peak Pulse Current",
  "peaks",
  "Peak-to-Peak",
  "Peak-to-Peak Amplitude",
  "Percent Bandwidth",
  "Percent Ripple",
  "Percent Saturation",
  "Period",
  "Periodic and Random Deviation",
  "peripheral equipment",
  "Peripheral Seal",
  "peripheral seal",
  "Permanent Virtual Circuit",
  "Permeability",
  "Permittivity",
  "peta",
  "PGA",
  "Phase",
  "Phase Angle",
  "phase control",
  "Phase Lock",
  "phase locked loop",
  "Phase Modulation",
  "Phase Modulator",
  "Phase Noise",
  "Phase Shift",
  "Phase Shifter",
  "phase splitter",
  "phenolic",
  "photodetector",
  "photoresist",
  "PHS",
  "pi",
  "Pick",
  "pickup value",
  "pico",
  "Pi-Filter",
  "pigments",
  "Pigtail",
  "Pigtail",
  "pin contact",
  "p-i-n Diode",
  "pin grid array",
  "Pin photodiode",
  "Pinch-Off",
  "Pinch-Off Voltage",
  "pinholes",
  "Pistoning",
  "pits",
  "planar",
  "plastic",
  "Plastic Deformation",
  "Plastic fiber",
  "Plastic-clad silica fiber",
  "plasticizers",
  "plated-thru hole",
  "Plating",
  "PLD",
  "Plenum",
  "Plenum cable",
  "Plug",
  "plug",
  "Plug Connector",
  "PM",
  "PMOS",
  "PNP (p-n-p) Transistor",
  "pnp transistor",
  "Point Contact",
  "point-to-point connection",
  "Poke Through",
  "Polarity",
  "polarization",
  "polarizing pin",
  "pole",
  "poly",
  "Polyamide",
  "polybutadiene",
  "polyethylene",
  "polyimide",
  "polymer",
  "polymerize",
  "Polyolefin",
  "polypropylene",
  "PolySwitch Resettable Devices",
  "polyurethane",
  "polyvinyl butyral",
  "polyvinyl chloride",
  "POP",
  "Port",
  "Positive feedback",
  "positive lock",
  "positive logic",
  "Positive Temperature Coefficient",
  "Post Regulation",
  "Post Tuning Drift",
  "Postal, Telegraph and Telephone Company",
  "Post-Reflow Resistance",
  "Post-Reflow Resistance",
  "Post-Trip Resistance",
  "Post-Trip Resistance",
  "pot",
  "potentiometer",
  "POTS",
  "potting",
  "Powdered Iron Core",
  "Power",
  "Power Amplifier",
  "Power Density",
  "Power Dissipation",
  "Power Divider",
  "Power Factor Correction",
  "Power Good",
  "Power Loss Density (mW/cm3)",
  "Power Rating",
  "Power sum",
  "Power Switch",
  "Power Transformer",
  "PPS",
  "PPTC Device",
  "PPTC Technology",
  "precision formed contact",
  "Pre-etching",
  "Preform",
  "pressure differential",
  "Pretinned",
  "Pretinned Solder Cup",
  "Primary Circuits",
  "Primary Current",
  "Primary Insulation",
  "Primary Winding",
  "printed circuit",
  "printed circuit assembly",
  "printed circuit board",
  "printed circuit edge connector",
  "printed components",
  "printed contact",
  "printed element",
  "printed wiring",
  "printed wiring board",
  "printing",
  "PRN",
  "processor",
  "Production Control",
  "production model",
  "program",
  "programmable memory",
  "programming",
  "programming system",
  "PROM",
  "propagation delay",
  "Propagation delay skew",
  "propagation delay time",
  "protocol",
  "prototype",
  "PS ELFEXT",
  "PS NEXT",
  "psi",
  "PTC",
  "PTD",
  "p-type",
  "p-type conductivity",
  "P-type Material",
  "p-type semiconductor",
  "pull out",
  "pull strength",
  "pull test",
  "pulse",
  "pulse broadening",
  "Pulse spreading",
  "Pulse Transformers",
  "pulse width",
  "Pulse Width Modulation",
  "Pulse-coded modulation",
  "pulseforming network",
  "Punchdown",
  "Pure Inductors",
  "purple plague",
  "Push-back",
  "Push-Pull",
  "Push-Pull Converter",
  "PVC",
  "PVDF",
  "pwb",
  "Q",
  "Q Factor",
  "QAM",
  "QPSK",
  "Quadrature",
  "Quality Assurance",
  "Quality Control",
  "quantizer",
  "Quantum efficiency",
  "queue",
  "Quick Disconnect",
  "Quiescent operating point",
  "QUIP",
  "R",
  "R1max",
  "RA Flux",
  "Ra max",
  "Ra min",
  "rack",
  "rack and panel connector",
  "Radiated Frequency",
  "Radiation Crosslinking",
  "Radio",
  "Radio Frequency",
  "RADSL",
  "RAIM",
  "RAM",
  "random-access memory",
  "Rated Current",
  "Rated Temperature",
  "Rated Voltage",
  "Ratio",
  "raw data",
  "Raychem Product Number",
  "Rayleigh scattering",
  "RC filter",
  "RC, RC circuit",
  "Reactance",
  "read",
  "read out",
  "read-only memory",
  "real-time operation",
  "Rear Release Contacts",
  "Receiver Protector",
  "Receiver Sensitivity",
  "Receptacle",
  "record",
  "Recover (Heat-shrinkable Components)",
  "Recovered ID",
  "Recovery Temperature",
  "Recovery Time",
  "rectification",
  "Rectifier",
  "redundancy",
  "Reduntant Operation",
  "reflection",
  "Reflection Coefficient",
  "reflection coefficient",
  "Reflection Loss",
  "reflective codes",
  "refractive index",
  "Regenerative repeater",
  "Regional Bell Operating Companies",
  "register",
  "register mark",
  "Regulation",
  "relay",
  "relay contact bounce",
  "Reliability",
  "Remote LAN Access",
  "Remote Sensing",
  "Remote Shutdown",
  "Removable Contact",
  "Repeater",
  "Repetition Rate",
  "reset",
  "Residual Flux",
  "Residual FM",
  "residual forces",
  "resiliency",
  "resist",
  "Resistance",
  "Resistance bias",
  "Resistance Binned Devices",
  "Resistance Sorted Devices",
  "resistor",
  "resonance",
  "Resonant Converter",
  "Resonant Frequency",
  "Responsivity",
  "restricted entry",
  "retaining ring",
  "retaining spring",
  "RETMA",
  "Return",
  "Return loss",
  "Return reflection",
  "Return reflection loss",
  "Reverse Current",
  "Reverse Voltage Protection",
  "Reversible Temperature Coefficient",
  "Rex Univariable Whisker Press",
  "RF",
  "RF Frequency",
  "RF Impedance",
  "RFI",
  "RFP",
  "RG/U",
  "rib",
  "Ribbon Cable",
  "ribbon cable",
  "RID",
  "right-angle edge connector",
  "ring counter",
  "Ring network",
  "Ripple",
  "Ripple and Noise",
  "Ripple Voltage",
  "rise time",
  "Riser",
  "RJ11",
  "RJ21",
  "RJ45",
  "RMA Flux",
  "Rmax",
  "RMC",
  "Rmin",
  "rms",
  "robotics",
  "roentgen",
  "ROM",
  "root mean square",
  "Rope Lay",
  "rotary switch",
  "rotor",
  "routine",
  "Royer Converter",
  "RPN",
  "RS 232, 422, 449+A2043",
  "RT and RW specifications",
  "RTCA",
  "RTCM",
  "RTK",
  "rubber",
  "RZ data rates",
  "SA",
  "safetying",
  "Saturable Reactor",
  "Saturated",
  "saturation",
  "Saturation",
  "Saturation Current",
  "Saturation Flux Density",
  "SAW",
  "S-band",
  "SC connector",
  "Scalar",
  "scale factor",
  "scanner",
  "SCD",
  "schematic",
  "Schmitt trigger",
  "Schottky",
  "Schottky TTL",
  "Scoop-proof",
  "scratch pad memory",
  "screw-machine contact",
  "scribing",
  "SD",
  "SDH",
  "SDLC",
  "SDSL",
  "SE",
  "Sealant",
  "Sealed",
  "sealing plug",
  "Secant Modulus",
  "Secondary Circuit",
  "Secondary Winding",
  "sector",
  "selective plating",
  "Self Resonant Frequency",
  "self-aligning",
  "self-extinguishing",
  "Self-Inductance",
  "Self-Powered Hub",
  "SEM",
  "semiconductor",
  "semiconductor device",
  "semi-rigid",
  "Sendust",
  "Sense Line",
  "sensitivity",
  "sensitivity switch",
  "separable part",
  "separating force",
  "sequencer",
  "sequencing",
  "serial memory",
  "serial operation",
  "serial transfer",
  "serial transmission",
  "series",
  "Series Operation",
  "Series Regulator",
  "Series Resistance",
  "Series-Shunt",
  "serrations",
  "Service Life",
  "Service Loop",
  "Service Rating",
  "Set Up Transformer",
  "Settling Time",
  "S-HDSL",
  "sheath",
  "Shelf Life",
  "Shell",
  "shf",
  "Shield",
  "Shielded Inductor",
  "shielded keyboard",
  "shielded room",
  "shielding",
  "shielding effectiveness",
  "shift",
  "shift register",
  "shock",
  "Shore",
  "Short Circuit Protection",
  "Shot noise",
  "Shrink Ratio",
  "Shunt",
  "Shunt Regulator",
  "SHV",
  "Sideband Suppression",
  "sign bit",
  "Signal Cable",
  "Signal Frequency",
  "Signal Rise Time",
  "signal-to-noise ratio",
  "significant digit",
  "silicon",
  "silicon dioxide",
  "silicon nitride",
  "silicon oxide",
  "silicon-controlled rectifier",
  "silicon-controlled switch",
  "silo",
  "Simple Network Management Protocol",
  "Simple Winding",
  "simplex",
  "Simplex cable",
  "Simplex transmission",
  "sine wave",
  "Single Ended Mixer",
  "Single Layer Winding",
  "single mode",
  "Singlemode",
  "Single-mode fiber",
  "single-pole",
  "Sintered Iron",
  "Six-Sided Shielding",
  "Skew",
  "Skewing Of The Loop",
  "Skin Effect",
  "sleeve",
  "slotted tongue",
  "Slug Core",
  "SMA connector",
  "Small Signal",
  "Small Signal Analysis",
  "small-scale integration",
  "SMD",
  "Smith Chart",
  "SMO",
  "SMR",
  "SMS",
  "Snap Time",
  "SNR",
  "socket contact",
  "Soft Magnetic Material",
  "Soft Start",
  "software",
  "SOG",
  "SOHO",
  "Solder",
  "solder",
  "Solder Contact",
  "Solder Cup",
  "Solderability",
  "solder-eyelet",
  "Soldering",
  "solderless",
  "SolderSleeve Device",
  "solenoid",
  "Solid Conductor",
  "Solid State",
  "Soliton",
  "Solvent Resistance",
  "Solvent Resistance Test",
  "Solvent Resistance Test",
  "SOM",
  "SONET",
  "sophisticated",
  "Sorted",
  "Source",
  "spade",
  "Spanning Tree",
  "Spare Inputs",
  "Sparkover",
  "SPC",
  "SPC",
  "spdt",
  "specific gravity",
  "Specific Inductive Capacity",
  "Specification Control Drawing",
  "specs",
  "spectral dispersion",
  "SPICE",
  "Splice",
  "Splitter",
  "spring properties",
  "spring-finger action",
  "SPS",
  "spst",
  "Spurious",
  "sputtering",
  "Square Wave",
  "Square-Law Detection",
  "Square-Law Detector",
  "Squareness Ratio",
  "SRF",
  "SSI",
  "ST connector",
  "stamped and formed contact",
  "Standby Current",
  "Standing Wave Ratio",
  "Standing Waves",
  "standing-wave",
  "standing-wave ratio",
  "Star coupler",
  "Star network",
  "start of message",
  "start sentinel",
  "State Machine",
  "Statistical Process Control",
  "statistical quality control",
  "stator",
  "Steady state",
  "Step Change",
  "Step Down Transformer",
  "step index",
  "Step-index fiber",
  "stop sentinel",
  "storage",
  "Storage Temperature Range",
  "STP",
  "Strain Relief",
  "strain relief clamp",
  "Strand",
  "Stranded Conductor",
  "Strength member",
  "Strip",
  "Stripe",
  "Stripline",
  "stud",
  "stud hole",
  "styrene-butadiene",
  "subassembly",
  "subminiaturization",
  "substrate",
  "subsystem",
  "SUPER CHAMP",
  "Super Compact",
  "superhigh frequency",
  "Supply Current",
  "Supply Voltage",
  "Surface Area",
  "Surface Resistance",
  "surface-mount device",
  "surge",
  "SV",
  "swedging",
  "Swing",
  "Swinging Inductors",
  "Switch",
  "Switch Mode Power Supply",
  "Switched Virtual Circuit",
  "Switching Frequency",
  "Switching Regulator",
  "Switching Time",
  "SWR",
  "Symmetrical Transmission",
  "synchronize",
  "synchronizer",
  "synchronous",
  "synchronous generator",
  "synchronous transmission",
  "system",
  "System Damage Voltage",
  "System/3X (IBM)",
  "T rise",
  "T1",
  "T2L",
  "T3",
  "T568A and B",
  "tab",
  "table",
  "Tab-Lok crimp",
  "tactile feedback",
  "tap (network)",
  "Tap loss",
  "Tap port",
  "tape memory",
  "Tape Wound Core",
  "Tape Wound Cores",
  "Tape Wrap",
  "tape-mounted",
  "taper pin",
  "target area",
  "TC",
  "tcr",
  "TDM",
  "TDMA",
  "TDMA",
  "TDOP",
  "Tear Test",
  "Technischer Uberwachungs-Verin (TUV)",
  "Tee coupler",
  "Telco",
  "Telco connector",
  "Telecom closet",
  "telecommunication",
  "Telecommunications Transformers",
  "Telecommuter",
  "telpak",
  "temperature coefficient",
  "Temperature Coefficient Of Inductance",
  "temperature coefficient of linear expansion",
  "Temperature Factor (TF)",
  "Temperature Range",
  "Temperature Rating",
  "temperature rise",
  "Tempest",
  "tensile",
  "tensile strength",
  "tera",
  "Terahertz",
  "Terapin",
  "Termal Conductivity",
  "terminal",
  "terminal area",
  "terminal barrel",
  "terminal strip",
  "Termination",
  "terminus",
  "terpolymer",
  "Tesla",
  "Test Frequency",
  "TETRA-CRIMP tools",
  "thermal compression bond",
  "Thermal Conductivity",
  "Thermal Derating",
  "thermal expansion",
  "Thermal Gasket",
  "Thermal Joint Compound",
  "Thermal noise",
  "Thermal Protection",
  "Thermal Rating",
  "thermal rating",
  "Thermal Resistance",
  "Thermal Resistivity",
  "thermal shock",
  "Thermal Shock Test",
  "thermal timedelay switch",
  "Thermochromic Indicator",
  "Thermoplastic",
  "thermoplastic elastomer",
  "Thermoset",
  "Thermosetting Adhesive",
  "Thermosetting plastic",
  "Thick Film",
  "thick film circuit",
  "Thicknet",
  "Thin Film",
  "thin film circuit",
  "Thinnet",
  "Three-Terminal Regulator",
  "Throughput loss",
  "Throughput port",
  "Thyristor",
  "time-delay",
  "time-delay relay",
  "time-delay switch",
  "time-division multiplexing",
  "timeshare",
  "Time-to-Trip",
  "tinning",
  "TNC Series connector",
  "TO can",
  "Token ring",
  "Tolerance",
  "tone-encoded keyboard",
  "Toroid",
  "Toroidal Inductor",
  "Trace Capacitance",
  "Traceability",
  "track",
  "tracking",
  "Tracking",
  "transfer molding",
  "Transformer",
  "Transient",
  "Transient Recovery Time",
  "Transient Suppression",
  "transients",
  "transistance",
  "transistor",
  "Transition Time",
  "Transmission Cable",
  "Transmission Control Protocol/Internet Protocol (TCP/IP)",
  "Transmission Line",
  "Transparent LAN Service",
  "TRAPATT",
  "TRI",
  "triac",
  "Triaxial Cable",
  "trimming",
  "Trip",
  "Trip Current",
  "Trip Cycle",
  "Trip Cycle Life",
  "Trip Time",
  "Tri-State",
  "TRK",
  "TRN",
  "truth table",
  "TTFF",
  "TTL",
  "TtT",
  "Tuning Monotonicity",
  "Tunnel Diode",
  "Turn Ratio",
  "Twisted Pair",
  "Twisted pair cable",
  "two-piece connector",
  "two-piece contact",
  "Two-tone Third-Order Intermodulation Distortion",
  "UADSL",
  "UDP",
  "UG",
  "uhf",
  "UL",
  "ultrahigh frequency",
  "ultrasonic bond",
  "ultrasonic welding",
  "ultraviolet curing",
  "Ultraviolet Degradation",
  "umbilical connector",
  "UMTS",
  "Uncertainty",
  "Undershoot",
  "Undervoltage lockout",
  "Underwriters Laboratory",
  "U-NII",
  "Uninterruptible Power Supply",
  "UNIX",
  "Upconverter (Mixer)",
  "UPS",
  "UTC",
  "UTM",
  "UTP",
  "UV",
  "UVLO",
  "Vac",
  "vacuum evaporation",
  "Varactor",
  "Varactor-tuned Oscillator",
  "variable",
  "Varistor",
  "VCC",
  "VCO",
  "Vdc",
  "VDE",
  "VDOP",
  "VDSL",
  "Vector",
  "Vector Modulator",
  "Velocity of Propagation",
  "Verband Deutscher Elektrontechniker",
  "very high frequency",
  "very-large-scale integration",
  "vhf",
  "VHSIC",
  "Vias",
  "vibration",
  "Video",
  "Video Impedance",
  "vinyl",
  "viscosity",
  "VLSI",
  "Vmax",
  "VMG",
  "VOD",
  "VoDSL",
  "voice-frequency",
  "VoIP",
  "volatile memory",
  "volt",
  "Volt Microsecond Constant",
  "Voltage",
  "Voltage Balance",
  "Voltage Breakdown",
  "Voltage Controlled Oscillator",
  "voltage drop",
  "Voltage Rating",
  "voltage regulator",
  "Voltage Standing Wave Ratio)",
  "Voltage Tuned Filter",
  "Volt-Ampere",
  "Volt-Microsecond Constant",
  "Volume Resistivity",
  "VPN",
  "VSAT",
  "VSWR",
  "VTF",
  "VTG",
  "vulcanization",
  "VW-1",
  "W crimp",
  "WAAS",
  "Wafer",
  "WAG",
  "Wall Thickness",
  "WAN",
  "Warmup Drift",
  "warmup time",
  "warp",
  "Water Absorption Test",
  "Water Blocking",
  "watt",
  "wattage rating",
  "Wave",
  "wave soldering",
  "Waveform",
  "Waveguide",
  "Wavelength",
  "WBI",
  "WCDMA",
  "Weber",
  "wedge bond",
  "welded circuit",
  "Wetting",
  "WGS84",
  "White Noise",
  "wicking",
  "Wideband",
  "Wilkinson Splitter",
  "Winchester disk",
  "Winding Factor (K)",
  "Window Area (Wa)",
  "wiping action",
  "wire",
  "wire barrel",
  "Wire Bonding",
  "wire crimp",
  "Wire Dress",
  "wire nut",
  "wire size",
  "wire stop",
  "Wire Wrap",
  "Wiring closet",
  "Withstanding Voltage",
  "WLAN",
  "WLL",
  "word",
  "word length",
  "word time",
  "Work area",
  "work harden",
  "wrap type",
  "write",
  "X",
  "X-Axis",
  "xDSL",
  "Xistor",
  "XML",
  "Xstr",
  "XTE",
  "XTK",
  "Y",
  "Y-Axis",
  "yield",
  "y-Parameter",
  "Z",
  "Z0",
  "Zener Diode",
  "zero voltage switch",
  "zero-suppression",
  "ZIF",
  "Zone cabling",
  "z-Parameter",
];

var tip =
    'Technical language barriers are quite commonplace today, and most of us have been confronted with at least a few elements of such a barrier from time to time. Advances in technology, and the introduction of new or unfamiliar product areas, all require an expansion of our technical vocabulary if we are to communicate effectively. Hopefully, this edition of the Glossary will serve as a valuable reference for improved communications';
